services:
  postgres:
    image: postgis/postgis:17-3.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=geoserver
      - POSTGRES_PASSWORD=geoserver
      - POSTGRES_DB=vectors
  geoserver:
    image: kartoza/geoserver:2.22.2
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_DATA_DIR=/opt/geoserver/data
      - STABLE_EXTENSIONS=css-plugin
    command: run
    volumes:
      - /opt/geoserver/data:/opt/geoserver/data
    restart: on-failure