services:
  postgis:
    image: postgis/postgis:17-3.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=geoserver
      - POSTGRES_PASSWORD=geoserver
      - POSTGRES_DB=vectors
    volumes:
      - ./internal/testdata/migrations/table_for_feature.sql:/docker-entrypoint-initdb.d/table_for_feature.sql
  geoserver-for-tests:
    image: kartoza/geoserver:2.22.2
    ports:
      - "1112:8080"
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_DATA_DIR=/opt/geoserver/data
      - STABLE_EXTENSIONS=css-plugin
    command: run
    volumes:
      - /tmp/data:/opt/geoserver/data:rw
    restart: always
  geoserver:
    image: kartoza/geoserver:2.22.2
    ports:
      - "1111:8080"
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_DATA_DIR=/opt/geoserver/data
      - STABLE_EXTENSIONS=css-plugin
    command: run
    volumes:
      - /opt/geoserver/data:/opt/geoserver/data
    restart: always