name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgis:
        image: postgis/postgis:17-3.5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: geoserver
          POSTGRES_PASSWORD: geoserver
          POSTGRES_DB: vectors
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      geoserver:
        image: kartoza/geoserver:2.22.2
        ports:
          - 1112:8080
        env:
          GEOSERVER_ADMIN_USER: admin
          GEOSERVER_ADMIN_PASSWORD: geoserver
          GEOSERVER_DATA_DIR: /opt/geoserver/data
          STABLE_EXTENSIONS: css-plugin

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod download

      - name: Wait for services to be ready
        run: |
          # Wait for PostgreSQL
          until PGPASSWORD=geoserver psql -h localhost -U geoserver -d vectors -c '\q'; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
          
          # Wait for GeoServer (more robust check)
          echo "Waiting for GeoServer to start..."
          timeout=300  # 5 minutes timeout
          elapsed=0
          until curl -s -f http://localhost:1112/geoserver/rest/about/version.json -u admin:geoserver > /dev/null 2>&1; do
            if [ $elapsed -ge $timeout ]; then
              echo "GeoServer failed to start within $timeout seconds"
              curl -v http://localhost:1112/geoserver/web/ || true
              docker logs $(docker ps -q --filter ancestor=kartoza/geoserver:2.22.2) || true
              exit 1
            fi
            echo "Waiting for GeoServer... ($elapsed/$timeout seconds)"
            sleep 10
            elapsed=$((elapsed + 10))
          done
          echo "GeoServer is ready!"
          
          echo "All services are ready!"

      - name: Copy SQL migration file
        run: |
          PGPASSWORD=geoserver psql -h localhost -U geoserver -d vectors -f ./internal/testdata/migrations/table_for_feature.sql

      - name: Run tests with coverage
        run: |
          CGO_ENABLED=1 go test -v -race -coverpkg=./... -coverprofile=coverage.out -covermode=atomic ./...
        env:
          # Set environment variables your tests might need
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: geoserver
          POSTGRES_PASSWORD: geoserver
          POSTGRES_DB: vectors
          GEOSERVER_URL: http://localhost:1112
          GEOSERVER_USER: admin
          GEOSERVER_PASSWORD: geoserver

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.out
          name: codecov-umbrella
          fail_ci_if_error: true